
# based on https://jekyllrb.com/docs/continuous-integration/travis-ci/
language: python
python:
  - "3.6"

install:
 - pip install -r scripts/parkrun-geo/requirements.txt

script:
   # Test fetch of the parkrun geo XML & Technical Event Info (both of which get
   # fetched and cached by the background script in the extenion)
   # The wiki page can be slow to load, or missing on occasion, so it would be
   # very useful to cache this away from parkrun's servers.
   # - python scripts/parkrun-geo/parkrun-geo.py
   - python scripts/parkrun-geo/parkrun-geo.py --output-data-dir ${TRAVIS_BUILD_DIR}/data/parkrun-geo
   # Get the special event information.
   - echo "${TRAVIS_BUILD_DIR}" && ls "${TRAVIS_BUILD_DIR}"
   - cd "${TRAVIS_BUILD_DIR}/data/parkrun-special-events" && ./fetch.sh && python ${TRAVIS_BUILD_DIR}/scripts/parkrun-special-events/parkrun-special-events.py --data-dir="${TRAVIS_BUILD_DIR}/data/parkrun-special-events"
   - cd ${TRAVIS_BUILD_DIR}/ && ${TRAVIS_BUILD_DIR}/scripts/github/commit-and-push-data.sh


# Branch Configuration
# Only build on the master branch, and we have configured Travis to never build
# on pushes, so nothing else should trigger the build apart from cron, or a manual
# trigger.

# We can detect what triggered a build by looking at the `TRAVIS_EVENT_TYPE`
# variable, which will be `cron` when it was triggered by the daily build.
# https://docs.travis-ci.com/user/cron-jobs#detecting-builds-triggered-by-cron
branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build
